### ISSUE TITLE
Lists too long for PANOS DBL

### ISSUE THREAD

**Issue by gaultx** [jtschichold/panwdbl#2]
The DBL feature in recent versions of PANOS 6.1.x have a max limit of 5000 lines. The larger lists should be parsed and broken into multiples of 5k lines to be functional in the PA.

**Comment by jtschichold** [comment]
Hi gaultx,
you can use the 'n' and 's' parameter to split the list in multiple sublists and cope with platform limits. Example:
http://panwdbl.appspot.com/lists/openbl.txt?n=20 => first 20 entries of openbl.txt list
http://panwdbl.appspot.com/lists/openbl.txt?n=20&s=20 => entries from 20 to 40 of openbl.txt

**Comment by gaultx** [comment]
True! I saw this feature and didn't take a moment to consider its application here.
I would recommend making a mention of PAN-OS' limit on this on the site though, in case someone doesn't read the help.

Thanks for the site.
